### ISSUE TITLE
GGally reverse dependency test check failure

### ISSUE THREAD

**Issue by schloerke** [carlopacioni/vortexR#38]
Hi @carlopacioni,

I'm doing a reverse dependency check before my release and am running into an error.

With some GGally updates, the test at [tests/testthat/test-plot.R#L65](https://github.com/carlopacioni/vortexR/blob/master/tests/testthat/test-plot.R#L65) is failing.  Since the line afterwards is checking if the `'ggmatrix'` object exists, I think it is ok to remove this check.

Thank you,
Barret

**Comment by carlopacioni** [comment]
Hi Barret,
Done! ...and pushed the changes now. Are you in rush for me to send this to CRAN? I'm almost done with some changes (see branch SSMD_matrix) and should be able to send it off to CRAN in the next couple of days.

carlo

**Comment by schloerke** [comment]
Hi Carlo,

If you can let me know when you're on CRAN, that would be great!

I was told by Uwe to serve me "two weeks notice" to make changes today. If
you're on CRAN before the two weeks are up, awesome!

Thank you for the quick response.

Best,
Barret

**Comment by carlopacioni** [comment]
On its way to CRAN now.

cheers,
carlo

**Comment by carlopacioni** [comment]
Hi Barret,
All done! The new version of VortexR should be up on cran in the next 24hr.
Cheers
Carlo

-----Original Message-----
