### ISSUE TITLE
Error: package or namespace load failed for 'vortexR'

### ISSUE THREAD

**Issue by faresdhane** [carlopacioni/vortexR#41]
Hi,

I'm trying to download the package, I followed all the steps (JDK, Java, libraries rJava and glmulti) but I always have the same issue, it doesn't work.

R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] forcats_0.5.0   stringr_1.4.0   dplyr_0.8.5     purrr_0.3.3     readr_1.3.1     tidyr_1.0.2    
[7] tibble_3.0.0    ggplot2_3.3.0   tidyverse_1.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     cellranger_1.1.0 pillar_1.4.3     compiler_3.6.3   dbplyr_1.4.2     tools_3.6.3     
 [7] lubridate_1.7.8  jsonlite_1.6.1   lifecycle_0.2.0  nlme_3.1-144     gtable_0.3.0     lattice_0.20-38 
[13] pkgconfig_2.0.3  rlang_0.4.5      reprex_0.3.0     cli_2.0.2        DBI_1.1.0        rstudioapi_0.11 
[19] haven_2.2.0      withr_2.1.2      xml2_1.3.1       httr_1.4.1       fs_1.4.1         generics_0.0.2  
[25] vctrs_0.2.4      hms_0.5.3        grid_3.6.3       tidyselect_1.0.0 glue_1.4.0       R6_2.4.1        
[31] fansi_0.4.1      readxl_1.3.1     modelr_0.1.6     magrittr_1.5     backports_1.1.6  scales_1.1.0    
[37] ellipsis_0.3.0   rvest_0.3.5      assertthat_0.2.1 colorspace_1.4-1 stringi_1.4.6    munsell_0.5.0  

and this is the error message:

There is a binary version available but the source version is later:
        binary source needs_compilation
vortexR  1.1.6  1.1.7             FALSE

installing the source package ‘vortexR’

trying URL 'http://cran.r-project.org/src/contrib/vortexR_1.1.7.tar.gz'
Content type 'application/x-gzip' length 695975 bytes (679 KB)
downloaded 679 KB

* installing *source* package 'vortexR' ...
** package 'vortexR' successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'vortexR'
    finding HTML links ... done
    CompileIter                             html  
    Nadults                                 html  
    Ne                                      html  
    Pextinct                                html  
    PrefixAndRepeat                         html  
    SSMD_matrix                             html  
    collate_dat                             html  
    collate_one_dat                         html  
    collate_proc_data                       html  
    collate_run                             html  
    collate_yr                              html  
    conv_l_yr                               html  
    df2disk                                 html  
    dot_plot                                html  
    fit_regression                          html  
    get_file_paths                          html  
    line_plot_year                          html  
    line_plot_year_mid                      html  
    lookup_table                            html  
    m_scatter                               html  
    pac.clas.Nadults                        html  
    pac.clas.Ne                             html  
    pac.clas                                html  
    pac.clas.lookup                         html  
    pac.clas.pairw                          html  
    pac.lhs                                 html  
    pac.run.lhs                             html  
    pac.yr                                  html  
    pairwise                                html  
    pval                                    html  
    rRec                                    html  
    se2sd                                   html  
    sta.evy5                                html  
    sta.evy5.b11                            html  
    sta.main                                html  
    vortexR                                 html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'vortexR':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/fsdha/Documents/R/win-library/3.6/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/fsdha/Documents/R/win-library/3.6/vortexR'
Warning in install.packages :
  installation of package ‘vortexR’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\fsdha\AppData\Local\Temp\RtmpU9lvYQ\downloaded_packages’

Any suggestion for how can I fix this problem?

**Comment by carlopacioni** [comment]
Hi,
it looks like something went wrong with the 32 bit installation of rJava,
probably you only have installed the 64 bit version of JDK. You should be
able to solve this by installing the 32-bit version of Java or, if you only
use the 64 bit of R, remove its 32 bit installation.

Cheers,
carlo

**Comment by faresdhane** [comment]
It worked!
Thank you.
Cheers

**Comment by carlopacioni** [comment]
;-)

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________
